# Server related config
server:
    port: 51232
    alias: pi4server

# Hardware IO related config
pins:
  - io:
      gpiochip: gpiochip0
      lineOffset: 5
      alias: GPIO5
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 6
      alias: GPIO6
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 12
      alias: GPIO12
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 13
      alias: GPIO13
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 16
      alias: GPIO16
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 17
      alias: GPIO17
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 18
      alias: GPIO18
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 19
      alias: GPIO19
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 20
      alias: GPIO20
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 21
      alias: GPIO21
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 22
      alias: GPIO22
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 23
      alias: GPIO23
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 24
      alias: GPIO24
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 25
      alias: GPIO25
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 26
      alias: GPIO26
      value: 0
      output: false
  - io:
      gpiochip: gpiochip0
      lineOffset: 27
      alias: GPIO27
      value: 0
      output: false
